import { useCallback, useEffect, useMemo, useState } from "react";
import AIAlertCard from "../components/AIAlertCard";
import ConfidenceScore from "../components/ConfidenceScore";
import PredictionChart from "../components/PredictionChart";
import RiskScoreCard from "../components/RiskScoreCard";
import ThreatPrediction from "../components/ThreatPrediction";
import { aiApi } from "../services/aiApi";

export default function AIThreatAnalysis() { const [state, setState] = useState({ loading: true, error: null, predictions: [], risks: [], alerts: [] }); const load = useCallback(async () => { try { const [predictions, risks, alerts] = await Promise.all([aiApi.predictions(), aiApi.risks(), aiApi.alerts()]); setState({ loading: false, error: null, predictions: predictions.data, risks: risks.data, alerts: alerts.data }); } catch (error) { setState((old) => ({ ...old, loading: false, error: error.message })); } }, []); useEffect(() => { load(); }, [load]); const confidence = useMemo(() => state.predictions[0]?.confidence_score || 0, [state.predictions]); return <main className="workspace"><header><div><p className="eyebrow">Sentinel AI · Phase 4</p><h1>AI Threat Analysis</h1><p>Defensive anomaly detection, classification, and explainable risk prediction.</p></div><span className="online">AI engine online</span></header>{state.loading ? <div className="state">Loading AI analytics…</div> : state.error ? <div className="state error"><strong>Unable to load AI analytics</strong><p>{state.error}</p><button onClick={load}>Retry</button></div> : <div className="grid"><RiskScoreCard risk={state.risks[0]}/><ConfidenceScore value={confidence}/><PredictionChart predictions={state.predictions} risks={state.risks}/><section className="panel predictions"><h2>Threat predictions</h2>{state.predictions.map((item) => <ThreatPrediction key={item.id} prediction={item}/>)}</section><section className="panel alerts"><h2>AI security alerts</h2>{state.alerts.length ? state.alerts.map((item) => <AIAlertCard key={item.id} alert={item}/>) : <p>No high-risk AI alerts.</p>}</section></div>}</main>; }
