import { useCallback, useEffect, useState } from 'react'
import { CheckCircle2, Clock3, RefreshCw, Siren } from 'lucide-react'
import { soarApi, unwrapList } from '../api/api'
import { EmptyState, ErrorState, LoadingState } from '../components/PageState'
import { PageHeader } from './Threats'

const workflow = ['Detection', 'Investigation', 'Response', 'Resolution']
export default function Incidents() {
  const [incidents, setIncidents] = useState([]); const [playbooks, setPlaybooks] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); const values = await Promise.allSettled([soarApi.incidents(), soarApi.playbooks()]); const next = values[0].status === 'fulfilled' ? unwrapList(values[0].value, ['incidents']) : []; setIncidents(next); if (values[1].status === 'fulfilled') setPlaybooks(unwrapList(values[1].value, ['playbooks'])); setError(values.every(value => value.status === 'rejected') ? values[0].reason.message : ''); setLoading(false) }, [])
  useEffect(() => { load(); const id = setInterval(load, 30000); return () => clearInterval(id) }, [load]); if (loading) return <LoadingState label="Loading SOAR response queue…" />; if (error) return <ErrorState message={error} onRetry={load} />
  return <div className="page"><PageHeader eyebrow="Phase 6 · Automated response" title="Incidents & SOAR Automation" text="Incident orchestration, active workflows, and automated containment." action={<button className="button secondary" onClick={load}><RefreshCw size={16}/>Refresh queue</button>} /><div className="split-summary"><div><span>Active incidents</span><strong>{incidents.length}</strong></div><div><span>Response playbooks</span><strong>{playbooks.length}</strong></div><div><span>Automation status</span><strong className="text-green">Enabled</strong></div></div>{incidents.length ? <section className="incident-stack">{incidents.map((incident, i) => <article className="panel incident-card" key={incident.id || i}><div className="incident-title"><Siren/><div><span className={`severity severity-${incident.severity || 'high'}`}>{incident.severity || 'high'}</span><h2>{incident.title || incident.name || 'Security incident'}</h2><p>{incident.description || 'Automated response workflow is monitoring this incident.'}</p></div><small><Clock3 size={13}/>{incident.created_at || 'Active now'}</small></div><div className="workflow">{workflow.map((step, stepIndex) => <div key={step} className={stepIndex < 2 ? 'complete' : ''}><span>{stepIndex < 2 ? <CheckCircle2/> : stepIndex + 1}</span>{step}</div>)}</div></article>)}</section> : <EmptyState title="No active incidents" message="SOAR is monitoring for new response-worthy detections." />}</div>
}
