import { BrainCircuit, ChevronRight } from 'lucide-react'
import { formatDate, severityOf } from './ThreatCard'

export default function AlertCard({ alert }) {
  const severity = severityOf(alert)
  return <article className="alert-row">
    <div className={`alert-symbol severity-${severity}`}><BrainCircuit size={18} /></div>
    <div className="alert-copy"><div><h3>{alert.title || alert.threat_type || alert.alert_type || 'AI security alert'}</h3><span className={`severity severity-${severity}`}>{severity}</span></div><p>{alert.description || alert.explanation || alert.event_id || 'Automated detection generated by the security pipeline.'}</p><small>{formatDate(alert.created_at || alert.detected_at || alert.timestamp)}</small></div>
    <div className="confidence"><strong>{alert.confidence ?? alert.risk_score ?? '—'}{typeof (alert.confidence ?? alert.risk_score) === 'number' ? '%' : ''}</strong><small>confidence</small></div><ChevronRight className="row-arrow" size={18} />
  </article>
}
