import { Bell, ChevronDown, Menu, Search } from "lucide-react";
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

const titles = { "/": "Security overview", "/threats": "Threat intelligence", "/alerts": "Alert operations", "/assets": "Protected assets", "/reports": "Security reports", "/settings": "Platform settings" };

export default function Navbar({ onMenu, timeRange, setTimeRange }) {
  const location = useLocation(); const navigate = useNavigate(); const [search, setSearch] = useState(""); const [popover, setPopover] = useState(null);
  const submitSearch = (event) => { event.preventDefault(); const destination = ["/threats", "/alerts", "/assets"].includes(location.pathname) ? location.pathname : "/threats"; navigate(`${destination}?search=${encodeURIComponent(search.trim())}`); };
  return <header className="navbar"><div className="nav-title"><button className="icon-button menu-button" onClick={onMenu} aria-label="Open navigation"><Menu/></button><div><p className="eyebrow">Security Operations Center</p><h1>{titles[location.pathname] || "SOC Console"}</h1></div></div><div className="nav-tools"><form className="search" onSubmit={submitSearch}><Search/><label className="sr-only" htmlFor="global-search">Search security data</label><input id="global-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search security data"/></form><label className="range-select"><span className="sr-only">Time range</span><select value={timeRange} onChange={(event) => setTimeRange(event.target.value)}><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select><ChevronDown/></label><div className="popover-wrap"><button className="icon-button notification" onClick={() => setPopover(popover === "notifications" ? null : "notifications")} aria-expanded={popover === "notifications"} aria-label="Notifications, 3 unread"><Bell/><span>3</span></button>{popover === "notifications" && <div className="nav-popover"><strong>Notifications</strong><p>3 alerts are awaiting analyst review.</p><button className="text-button" onClick={() => navigate("/alerts?status=new")}>Open alert queue</button></div>}</div><div className="system-status"><i/>Operational</div><div className="popover-wrap"><button className="profile" onClick={() => setPopover(popover === "profile" ? null : "profile")} aria-expanded={popover === "profile"} aria-label="Open profile menu"><span>DA</span><div><strong>Duty Analyst</strong><small>Tier 2</small></div><ChevronDown/></button>{popover === "profile" && <div className="nav-popover profile-popover"><strong>Duty Analyst</strong><p>Tier 2 · Defensive operations</p><button className="text-button" onClick={() => navigate("/settings")}>Open settings</button></div>}</div></div></header>;
}
