CREATE SCHEMA IF NOT EXISTS integration;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(512) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'analyst',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS security_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(120) NOT NULL,
    username VARCHAR(80) NOT NULL,
    status VARCHAR(20),
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    device_information VARCHAR(512),
    location_information VARCHAR(255),
    failure_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_ip VARCHAR(45) NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    description TEXT NOT NULL DEFAULT '',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type VARCHAR(120) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    username VARCHAR(80) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    attempt_count INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS threat_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ip VARCHAR(45) NOT NULL,
    threat_type VARCHAR(120) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS threat_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ip VARCHAR(45) NOT NULL,
    threat_type VARCHAR(120) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_log_id BIGINT NOT NULL UNIQUE REFERENCES security_logs(id) ON DELETE CASCADE,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    threat_level VARCHAR(20) NOT NULL,
    behavior_summary TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attack_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    threat_event_id BIGINT NOT NULL UNIQUE REFERENCES threat_events(id) ON DELETE CASCADE,
    source_ip VARCHAR(45) NOT NULL,
    path TEXT NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    risk_level VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PREDICTED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_type VARCHAR(120) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    response_action TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_users_username ON users(username);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_token_hash ON auth_sessions(token_hash);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_expires_at ON auth_sessions(expires_at);
CREATE INDEX IF NOT EXISTS ix_security_logs_timestamp ON security_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS ix_security_logs_severity ON security_logs(severity);
CREATE INDEX IF NOT EXISTS ix_security_logs_event_type ON security_logs(event_type);
CREATE INDEX IF NOT EXISTS ix_security_logs_status ON security_logs(status);
CREATE INDEX IF NOT EXISTS ix_security_logs_ip_address ON security_logs(ip_address);
CREATE INDEX IF NOT EXISTS ix_alerts_alert_type ON alerts(alert_type);
CREATE INDEX IF NOT EXISTS ix_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS ix_alerts_status_created_at ON alerts(status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_alerts_identity ON alerts(username, ip_address);
CREATE INDEX IF NOT EXISTS ix_threat_analyses_source_created ON threat_analyses(source_ip, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_threat_analyses_type_created ON threat_analyses(threat_type, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_threat_events_source_created ON threat_events(source_ip, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_threat_events_threat_type ON threat_events(threat_type);
CREATE INDEX IF NOT EXISTS ix_ai_detections_security_log_id ON ai_detections(security_log_id);
CREATE INDEX IF NOT EXISTS ix_attack_paths_threat_event_id ON attack_paths(threat_event_id);
CREATE INDEX IF NOT EXISTS ix_incidents_incident_type ON incidents(incident_type);
CREATE INDEX IF NOT EXISTS ix_incidents_status ON incidents(status);

CREATE TABLE IF NOT EXISTS integration.event_lineage (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    correlation_id UUID NOT NULL,
    source_phase SMALLINT NOT NULL CHECK (source_phase BETWEEN 1 AND 9),
    source_record_id VARCHAR(160) NOT NULL,
    target_phase SMALLINT CHECK (target_phase BETWEEN 1 AND 9),
    target_record_id VARCHAR(160),
    event_type VARCHAR(120) NOT NULL,
    schema_version VARCHAR(20) NOT NULL DEFAULT '1.0',
    status VARCHAR(30) NOT NULL DEFAULT 'received',
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_phase, source_record_id, target_phase, event_type)
);

CREATE TABLE IF NOT EXISTS integration.outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(160) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS integration.phase_health (
    phase SMALLINT PRIMARY KEY CHECK (phase BETWEEN 1 AND 9),
    status VARCHAR(30) NOT NULL,
    status_code INTEGER,
    details JSONB NOT NULL DEFAULT '{}',
    checked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_event_lineage_correlation ON integration.event_lineage(correlation_id);
CREATE INDEX IF NOT EXISTS ix_outbox_unpublished ON integration.outbox_events(created_at) WHERE published_at IS NULL;
