import { Activity, BellRing, ChevronRight, CircleGauge, Network, ShieldAlert } from 'lucide-react'

const alerts = [
  { name: 'Suspicious authentication pattern', source: '192.0.2.44', severity: 'Critical', time: '2m ago' },
  { name: 'IOC correlation match', source: '198.51.100.18', severity: 'High', time: '8m ago' },
  { name: 'Unusual access sequence', source: '203.0.113.72', severity: 'Medium', time: '14m ago' },
]

export function PlatformPreview() { return <section className="section preview" aria-labelledby="preview-title"><div className="container"><div className="section-heading section-heading--split"><div><span className="kicker">LIVE PLATFORM PREVIEW</span><h2 id="preview-title">A focused view for<br/><em>security operations.</em></h2></div><p>This illustrative interface mirrors the platform's SOC concepts without connecting to the backend. All values and addresses below are safe demo data.</p></div><div className="soc-window"><div className="soc-window__bar"><div className="soc-window__brand"><ShieldAlert/> SENTINEL / SOC OVERVIEW</div><div className="demo-badge">DEMO DATA</div><div className="soc-window__status"><i/> SYSTEM MONITORING</div></div><div className="soc-window__body"><aside className="soc-side" aria-label="Demo dashboard navigation"><span className="is-active"><CircleGauge/> Overview</span><span><BellRing/> Alerts</span><span><Network/> Assets</span><span><Activity/> Intelligence</span></aside><div className="soc-main"><div className="soc-title"><div><small>UNIFIED COMMAND CENTER</small><h3>Security posture</h3></div><span>Illustrative telemetry</span></div><div className="soc-metrics"><Metric label="Threat score" value="68" suffix="/100" tone="amber"/><Metric label="Active alerts" value="12" suffix="events" tone="red"/><Metric label="Monitored assets" value="248" suffix="systems" tone="cyan"/><Metric label="Phase health" value="8/9" suffix="available" tone="blue"/></div><div className="soc-grid"><div className="soc-chart panel-demo"><div className="panel-demo__title"><span>DETECTION ACTIVITY</span><small>LAST 24 HOURS</small></div><div className="chart-bars">{[28,42,35,58,49,73,62,86,68,75,54,64].map((height, i) => <i key={i} style={{height: `${height}%`}}/>)}</div><div className="chart-axis"><span>00:00</span><span>08:00</span><span>16:00</span><span>NOW</span></div></div><div className="risk-orbit panel-demo"><div className="panel-demo__title"><span>AI RISK ANALYSIS</span><small>BOUNDED SCORE</small></div><div className="risk-orbit__ring"><div><strong>68</strong><small>GUARDED</small></div></div></div></div><div className="alert-list panel-demo"><div className="panel-demo__title"><span>RECENT SECURITY ACTIVITY</span><small>DEMO DATA</small></div>{alerts.map(alert => <div className="demo-alert" key={alert.name}><i className={`severity-dot severity-dot--${alert.severity.toLowerCase()}`}/><div><strong>{alert.name}</strong><small>{alert.source} · {alert.time}</small></div><span>{alert.severity}</span><ChevronRight/></div>)}</div></div></div></div></div></section> }

function Metric({ label, value, suffix, tone }: { label: string; value: string; suffix: string; tone: string }) { return <div className={`soc-metric soc-metric--${tone}`}><span>{label}</span><strong>{value}</strong><small>{suffix}</small></div> }
