import { useCallback, useState } from "react";
import { useSearchParams } from "react-router-dom";
import AlertCard from "../components/AlertCard";
import Modal from "../components/Modal";
import Pagination from "../components/Pagination";
import { EmptyState, ErrorState, LoadingState } from "../components/PageState";
import SeverityBadge from "../components/SeverityBadge";
import { useApi } from "../hooks/useApi";
import { dashboardApi } from "../services/dashboardApi";
import { formatDate, titleCase } from "../utils";

export default function Alerts() {
  const [params, setParams] = useSearchParams(); const [selected, setSelected] = useState(null); const [toast, setToast] = useState(null); const query = Object.fromEntries(params); const loader = useCallback(() => dashboardApi.alerts({ page: query.page || 1, page_size: 8, search: query.search || undefined, severity: query.severity || undefined, status: query.status || undefined }), [params.toString()]); // eslint-disable-line react-hooks/exhaustive-deps
  const state = useApi(loader, [loader]); const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next); };
  const changeStatus = async (alert, status) => { if (!window.confirm(`${titleCase(status)} alert “${alert.title}”? This action is recorded.`)) return; try { await dashboardApi.updateAlertStatus(alert.id, status); setToast({ type: "success", message: `Alert ${titleCase(status)} successfully.` }); setSelected(null); state.retry(); } catch (error) { setToast({ type: "error", message: error.message }); } };
  return <><header className="page-heading"><div><p className="eyebrow">Analyst queue</p><h2>Alerts</h2><p>Acknowledge, investigate, resolve, and reopen security alerts.</p></div></header>{toast && <div className={`toast ${toast.type}`} role="status">{toast.message}<button onClick={() => setToast(null)} aria-label="Dismiss notification">×</button></div>}<div className="filters"><input value={query.search || ""} onChange={(e) => update("search", e.target.value)} placeholder="Search alerts" aria-label="Search alerts"/><select value={query.severity || ""} onChange={(e) => update("severity", e.target.value)} aria-label="Filter severity"><option value="">All severities</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select><select value={query.status || ""} onChange={(e) => update("status", e.target.value)} aria-label="Filter status"><option value="">All statuses</option><option>new</option><option>investigating</option><option>acknowledged</option><option>resolved</option></select></div>{state.loading ? <LoadingState/> : state.error ? <ErrorState error={state.error} retry={state.retry}/> : state.data.data.length === 0 ? <EmptyState/> : <section className="card alert-list">{state.data.data.map((alert) => <AlertCard key={alert.id} alert={alert} onDetails={setSelected} onStatusChange={changeStatus}/>)}</section>}<Pagination meta={state.data?.meta} onPage={(page) => update("page", page)}/>{selected && <Modal title={selected.title} onClose={() => setSelected(null)}><div className="detail-header"><SeverityBadge severity={selected.severity}/><span className={`status status-${selected.status}`}>{titleCase(selected.status)}</span></div><p>{selected.description}</p><dl className="details-grid"><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Asset</dt><dd>{selected.asset}</dd></div><div><dt>Created</dt><dd>{formatDate(selected.created_at)}</dd></div><div><dt>Updated</dt><dd>{formatDate(selected.updated_at)}</dd></div></dl><div className="modal-actions">{selected.status === "resolved" ? <button className="button" onClick={() => changeStatus(selected, "investigating")}>Reopen investigation</button> : <><button className="button secondary" onClick={() => changeStatus(selected, "acknowledged")}>Acknowledge</button><button className="button" onClick={() => changeStatus(selected, "resolved")}>Resolve</button></>}</div></Modal>}</>;
}
