import { useCallback, useState } from "react";
import { useSearchParams } from "react-router-dom";
import Modal from "../components/Modal";
import Pagination from "../components/Pagination";
import { EmptyState, ErrorState, LoadingState } from "../components/PageState";
import SeverityBadge from "../components/SeverityBadge";
import ThreatCard from "../components/ThreatCard";
import { useApi } from "../hooks/useApi";
import { dashboardApi } from "../services/dashboardApi";
import { formatDate, titleCase } from "../utils";

export default function Threats() {
  const [params, setParams] = useSearchParams(); const [selected, setSelected] = useState(null); const query = Object.fromEntries(params); const loader = useCallback(() => dashboardApi.threats({ page: query.page || 1, page_size: 8, search: query.search || undefined, severity: query.severity || undefined, status: query.status || undefined, threat_type: query.threat_type || undefined, sort_by: query.sort_by || "last_detected_at", sort_order: query.sort_order || "desc" }), [params.toString()]); // eslint-disable-line react-hooks/exhaustive-deps
  const state = useApi(loader, [loader]);
  const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); setParams(next); };
  const openDetails = async (threat) => { setSelected(threat); try { const result = await dashboardApi.threat(threat.id); setSelected(result.data); } catch { /* list data remains useful */ } };
  return <><header className="page-heading"><div><p className="eyebrow">Investigation workspace</p><h2>Threats</h2><p>Prioritize and review defensive detections.</p></div></header><div className="filters"><input value={query.search || ""} onChange={(e) => update("search", e.target.value)} placeholder="Search threats" aria-label="Search threats"/><select value={query.severity || ""} onChange={(e) => update("severity", e.target.value)} aria-label="Filter severity"><option value="">All severities</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select><select value={query.status || ""} onChange={(e) => update("status", e.target.value)} aria-label="Filter status"><option value="">All statuses</option><option>active</option><option>investigating</option><option>contained</option><option>resolved</option></select><select value={query.threat_type || ""} onChange={(e) => update("threat_type", e.target.value)} aria-label="Filter threat type"><option value="">All types</option><option>Identity anomaly</option><option>Endpoint behavior</option><option>Authentication anomaly</option><option>Data access anomaly</option></select><select value={query.sort_by || "last_detected_at"} onChange={(e) => update("sort_by", e.target.value)} aria-label="Sort threats"><option value="last_detected_at">Recently detected</option><option value="severity">Severity</option><option value="confidence_score">Confidence</option><option value="title">Title</option></select></div>{state.loading ? <LoadingState/> : state.error ? <ErrorState error={state.error} retry={state.retry}/> : state.data.data.length === 0 ? <EmptyState/> : <><div className="threat-grid">{state.data.data.map((threat) => <ThreatCard key={threat.id} threat={threat} onDetails={openDetails}/>)}</div><Pagination meta={state.data.meta} onPage={(page) => update("page", page)}/></>}{selected && <Modal title={selected.title} onClose={() => setSelected(null)}><div className="detail-header"><SeverityBadge severity={selected.severity}/><span>{selected.external_id} · {titleCase(selected.status)}</span></div><p>{selected.description}</p><dl className="details-grid"><div><dt>Confidence</dt><dd>{selected.confidence_score}%</dd></div><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Target</dt><dd>{selected.target_asset}</dd></div><div><dt>Last seen</dt><dd>{formatDate(selected.last_detected_at)}</dd></div></dl><h3>Detection evidence</h3><p>{selected.evidence}</p><h3>Suggested defensive response</h3><p>{selected.suggested_response}</p><h3>Activity timeline</h3><ol className="timeline">{selected.timeline?.map((event) => <li key={event}>{event}</li>)}</ol></Modal>}</>;
}
