import { useCallback, useEffect, useState } from "react";
import { ErrorState, LoadingState } from "../components/PageState";
import SeverityBadge from "../components/SeverityBadge";
import { threatIntelligenceApi } from "../services/threatIntelligenceApi";
import { formatDate } from "../utils";

export default function ThreatIntelligence() {
  const [state, setState] = useState({ loading: true, error: null });
  const load = useCallback(async () => { setState({ loading: true, error: null }); try { const [threats, vulnerabilities, indicators, logs, statistics] = await Promise.all([threatIntelligenceApi.threats(), threatIntelligenceApi.vulnerabilities(), threatIntelligenceApi.indicators(), threatIntelligenceApi.logs(), threatIntelligenceApi.statistics()]); setState({ loading: false, error: null, threats: threats.data, vulnerabilities: vulnerabilities.data, indicators: indicators.data, logs: logs.data, statistics: statistics.data }); } catch (error) { setState({ loading: false, error: error.message }); } }, []);
  useEffect(() => { load(); }, [load]);
  if (state.loading) return <LoadingState label="Loading threat intelligence"/>;
  if (state.error) return <ErrorState error={state.error} retry={load}/>;
  return <><header className="page-heading"><div><p className="eyebrow">Phase 3 intelligence engine</p><h2>Threat Intelligence</h2><p>Correlated vulnerabilities, indicators, and sanitized security events.</p></div></header><div className="summary-grid"><article className="card metric"><span>Total intelligence threats</span><strong>{state.statistics.total_threats}</strong></article><article className="card metric"><span>High-risk threats</span><strong>{state.statistics.high_risk_threats}</strong></article><article className="card metric"><span>Overall risk score</span><strong>{state.statistics.overall_risk_score}</strong></article></div><section className="card"><h3>Latest intelligence feed</h3><div className="table-wrap"><table><thead><tr><th>Threat</th><th>Type</th><th>Severity</th><th>Risk</th><th>Observed</th></tr></thead><tbody>{state.threats.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.source}</small></td><td>{item.type}</td><td><SeverityBadge severity={item.severity}/></td><td>{item.risk_score}/100</td><td>{formatDate(item.created_at)}</td></tr>)}</tbody></table></div></section><div className="content-grid"><section className="card"><h3>Vulnerabilities</h3>{state.vulnerabilities.map((item) => <article className="list-row" key={item.id}><div><strong>{item.cve_id}</strong><small>{item.affected_products.join(", ") || "Affected products unspecified"}</small></div><SeverityBadge severity={item.severity}/></article>)}</section><section className="card"><h3>Indicators of compromise</h3>{state.indicators.map((item) => <article className="list-row" key={item.id}><div><strong>{item.value}</strong><small>{item.indicator_type} · {item.threat_category}</small></div><span>{item.confidence_score}%</span></article>)}</section><section className="card"><h3>Recent security events</h3>{state.logs.map((item) => <article className="list-row" key={item.id}><div><strong>{item.event_type.replaceAll("_", " ")}</strong><small>{item.user_id} · {item.ip_address || "No IP"} · {formatDate(item.created_at)}</small></div><SeverityBadge severity={item.risk_level}/></article>)}</section></div></>;
}
