import { Architecture } from './components/Architecture'
import { CallToAction } from './components/CallToAction'
import { Capabilities } from './components/Capabilities'
import { Footer } from './components/Footer'
import { Hero } from './components/Hero'
import { Mission } from './components/Mission'
import { Navbar } from './components/Navbar'
import { PlatformPreview } from './components/PlatformPreview'
import { Problem } from './components/Problem'
import { Solution } from './components/Solution'
import { Technologies } from './components/Technologies'
import { TrustStrip } from './components/TrustStrip'
import { Workflow } from './components/Workflow'

export default function App() { return <><a className="skip-link" href="#main-content">Skip to content</a><Navbar/><main id="main-content"><Hero/><TrustStrip/><Problem/><Solution/><Capabilities/><PlatformPreview/><Workflow/><Architecture/><Technologies/><Mission/><CallToAction/></main><Footer/></> }
